### ISSUE TITLE
Add support for `mip` CSR emulation

### ISSUE THREAD

**Issue by CharlyCst** [CharlyCst/miralis#105]
We noticed that Linux doesn't boot properly on older QEMU versions (see #103), most likely because the CPU doesn't have the same features available as more recent QEMU versions.
While we work toward supporting the VisionFive2 board we might run into the same issues on the hardware, therefore this seems worth investigating.

**How to reproduce**

QEMU can take a `-cpu` argument to specify which CPU model it should use. I managed to reproduce the same failure as seen on the CI on a more recent QEMU version by passing `-cpu sifive-u54` as argument.

To reproduce first run Linux using `just run linux`. This will succeed on recent QEMU versions. Prior to running Miralis with the OpenSBI/Linux payload `just run linux` will print the QEMU command used, something similar to:

```sh
qemu-system-riscv64 --no-reboot -nographic -machine virt -bios .....
```

Copy this command and add `-cpu sifive-u54` at the end, which will trigger the `mip` emulation issue:

```
Boot HART ID              : 0
Boot HART Domain          : root
Boot HART Priv Version    : v1.12
Boot HART Base ISA        : rv64ima
Boot HART ISA Extensions  : zihpm
Boot HART PMP Count       : 8
Boot HART PMP Granularity : 2 bits
Boot HART PMP Address Bits: 54
Boot HART MHPM Info       : 0 (0x00000000)
Boot HART MIDELEG         : 0x0000000000000222
Boot HART MEDELEG         : 0x000000000000b109
[Error | miralis] Panicked at PanicInfo {
    payload: Any { .. },
    message: Some(
        mip emulation is not yet implemented,
    ),
    location: Location {
        file: "src/virt.rs",
        line: 740,
        col: 21,
    },
    can_unwind: true,
    force_no_backtrace: false,
}
[Info  | miralis::debug] Maximal stack usage: 20536 bytes (62.27%)
```

Note: once `mip` is supported we can add Linux back in the CI test workflow.

**Comment by NoeTerrier** [comment]
By allowing the firmware to set mip (#111) I can pass over this particular panic, but I get stuck further on. 
To reproduce, checkout branch `105-support-for-mip-csr` and add  `-cpu sifive-u54` to the runner options. 

To debug, break once at address 0xffffffff8000a2fa, continue three time, break at metal.rs:353 (`switch_from_firmware_to_payload`), continue.
At this point:

$mcause is set to 0x7 by a previous trap in `_raw_trap_handler`
$mie is 0 and become 0x8a
$mip is 0x80 (MTIP)
$mideleg.MTIE & $mie.MTIE = 0 -> It traps

I think an interrupt append when transitioning between firmware and payload. Do we want to disable interrupt when doing the transition ?

```
Boot HART ID              : 0
Boot HART Domain          : root
Boot HART Priv Version    : v1.12
Boot HART Base ISA        : rv64ima
Boot HART ISA Extensions  : zihpm
Boot HART PMP Count       : 8
Boot HART PMP Granularity : 2 bits
Boot HART PMP Address Bits: 54
Boot HART MHPM Info       : 0 (0x00000000)
Boot HART MIDELEG         : 0x0000000000000222
Boot HART MEDELEG         : 0x000000000000b109
[Error | miralis] Unexpected trap while executing Miralis
[Error | miralis]   cause:   7 (store/amo access fault)
[Error | miralis]   mepc:    0x800000e4
[Error | miralis]   mtval:   0x1f33eb4aa5614b6
[Error | miralis]   mstatus: 0xa00001822
[Error | miralis]   mip:     0x80
[Error | miralis] Panicked at PanicInfo {
    payload: Any { .. },
    message: Some(
        not yet implemented: Miralis trap handler entered,
    ),
    location: Location {
        file: "src/main.rs",
        line: 176,
        col: 5,
    },
    can_unwind: true,
    force_no_backtrace: false,
} 
[Info  | miralis::debug] Maximal stack usage: 20744 bytes (63.33%)
```

**Comment by NoeTerrier** [comment]
After investigation, it seems that we need two things: prevent global interrupt to be enable when running Miralis, and trick the time for the CLINT mtimecmp register to be a bit above what Linux want to write, in `device.rs::write_clint`

```rust
o if o >= clint::MTIMECMP_OFFSET && o < clint::MTIME_OFFSET => {
                let hart = (o - clint::MTIMECMP_OFFSET) / clint::MTIMECMP_WIDTH;
                if value < usize::MAX {
                    driver.write_mtimecmp(hart, value + 100_000)
                } else {
                    driver.write_mtimecmp(hart, value)
                }
            }
```
