### ISSUE TITLE
`hart_id` Variable Mismatch on VisionFive2 Board

### ISSUE THREAD

**Issue by Wesdcv** [CharlyCst/miralis#122]
#### Description
On the VisionFive2 board, the `hart_id` variable does not correspond to the `mhartid` register value after parking the cores. 

#### Steps to Reproduce
1. Check the values for the following code snippet (`main.rs`):
    ```rust
    pub(crate) extern "C" fn main(hart_id: usize, device_tree_blob_addr: usize) -> ! {
        // For now we simply park all the harts other than the boot one
        if hart_id != Plat::get_primary_hart() {
            loop {
                Arch::wfi();
                core::hint::spin_loop();
            }
        }
    }
    ```
2. Observe that `hart_id` gets the value 4, but `Arch::read_csr(Csr::Mhartid)` after the loop returns 1*.
(*) 1 is just the current configured value for `Plat::get_primary_hart()` on VisionFive2 platform.

#### Additional Context
- Commit: `b822f7fe01de20baf3fd850ffa30bc620925a3a4`
- If `Arch::read_csr(Csr::Mhartid)` is read before the loop, it returns 4. However, if read after the loop, it returns 1:
    ```rust
    pub(crate) extern "C" fn main(hart_id: usize, device_tree_blob_addr: usize) -> ! {
      let hart_id = Arch::read_csr(Csr::Mhartid); // here it reads as 4
        if hart_id != Plat::get_primary_hart() { // for some reason the loop is passed correctly only by primary hart
            loop {
                Arch::wfi();
                core::hint::spin_loop();
            }
        }
        let hart_id = Arch::read_csr(Csr::Mhartid); // here it reads as 1
    }
    ```
- By value i mean the output in the logs after the loop: `log::info!("Hart ID: {}", hart_id);`

**Comment by NoeTerrier** [comment]
Closing issues #124 and #164 seems to have removed the problem.
