### ISSUE TITLE
What if we wan to run Miralis without firmware? 

### ISSUE THREAD

**Issue by francois141** [CharlyCst/miralis#179]
We're always launching Miralis with firmware.

In case there is no firmware. It seems that the code crashes directly (which is expected). @CharlyCst Does it seem realistic to you to think of this case where the firmware is non-existent / incorrectly loaded? If it doesn't seem important to you, feel free to close the issue. Otherwise I could create a pr that checks if the firmware is loaded correctly. I was just wondering if you'd ever thought about this scenario.

#### Log example

```bash
[Info  | miralis] Hello, world!
[Info  | miralis] Platform name: QEMU virt
[Info  | miralis] Hart ID: 0
[Info  | miralis] misa:    0x800000000014112d
[Info  | miralis] vmisa:   0x8000000000141101
[Info  | miralis] mstatus: 0xa00000000
[Info  | miralis] DTS address: 0x1020
[Info  | miralis] Preparing jump into firmware
[Error | miralis] Panicked at PanicInfo {
    payload: Any { .. },
    message: Some(
        not yet implemented: Instruction not yet implemented: Unknown 0 0,
    ),
    location: Location {
        file: "src/virt.rs",
        line: 320,
        col: 18,
    },
    can_unwind: true,
    force_no_backtrace: false,
} 
[Info  | miralis::debug] Maximal stack usage: 5616 bytes (17.71%)
``

**Comment by CharlyCst** [comment]
How did you execute Miralis? If you run `just run` without adding a firmware as argument it selects a firmware named `default`. This is the recommended way to start Miralis, that seems good enough to me.

We probably don't want Miralis itself do detect if there is a firmware or not (it's not possible do to it reliably), so having a default firmware like we do seems to be the easiest solution.

**Comment by francois141** [comment]
I executed it using spike :-) I see. Your answer makes sense. Therefore I close the issue
