### ISSUE TITLE
Create a ProtectPayload policy

### ISSUE THREAD

**Issue by CharlyCst** [CharlyCst/miralis#211]
We recently introduced an initial support for adding security policies to Miralis, which is still an exploratory concept in Miralis.
As part of the exploration, this issue proposes to implement a `ProtectPayload` whose goal is to protect the payload from the firmware.

The payload protection takes two forms:
- Memory protection: the firmware should not be able to access payload memory
- Register protection: the firmware should only be able to see a restricted set of register, as required for proper service. For instance general purpose registers should not be exposed when handling interrupts, but the registers `a0` to `a7` are available when handling an `ecall` (they are interpreted as the `ecall`'s arguments). We should also find a reasonable solutions for `csr` registers, but that can come as a second step.

Because the firmware performs some form of initialization and assists the payload during the boot, the idea of the `ProtectPayload` policy is to dynamically and irreversibly switch from an unprotected mode, where the firmware has full access to the payload, to a protected mode where the firmware looses access to the payload memory and registers.
I think that the simplest solution for performing the transition is to add a custom `ecall` that the payload can perform whenever it is ready.

Achieving this will require to extend the capabilities of the `PolicyModule` trait, in particular to reserve a PMP slot and to interpose on world switches to save registers.

==== EDIT fron @francois141 ====

After the first base is merged, we need have multiple subtasks

- [ ] Refactor PMP module
- [ ] Hide floating point registers
- [ ] Hide CSR registers
- [ ] Create a test payload that save its own registers before jumping

**Comment by francois141** [comment]
@CharlyCst I started having a look at that. It seems that if we want to implement this policy, we should definitively load the payload at 0x80400000 :-)

I will start investigating tomorrow a good way to set up the pmps and I come back to you with a concrete plan
