### ISSUE TITLE
``Mcycle`` register doesn't get updated

### ISSUE THREAD

**Issue by francois141** [CharlyCst/miralis#219]
@CharlyCst We don't emulate the mcycle register correctly

**Comment by CharlyCst** [comment]
In general yes, we don't have emulation in place for performance counters.

Those would need some proper reflexion and clear design choices (e.g. do we want to allow counter the events in Miralis? How much overhead are we ready to introduce for performance counters emulation?), it is not a trivial feature.

**Comment by francois141** [comment]
@CharlyCst I think we need them to be able to benchmark the code. 

I don't see why we would not want to allow the counter events in Miralis, can you expain me your argument?

Regarding performance, we don't need a second trap, we can simply allow ready mcycle in U-mode. It seems there is something like that in the documentation.

**Comment by CharlyCst** [comment]
So this is a typical case where we would need to multiplex resources (e.g. the counters) across multiple contexts.

Miralis itself might want to use the performance counters (and we do when enabling benchmarking in the config), the firmware and the payload might want to use them too. So we have a finite set of registers that we need to share among Miralis and the firmware/payload. If we don't do this we might create conflicts and unpredictable results (e.g. the firmware resetting the counters used by Miralis).

We already multiplex some resources, such as the PMP for instance (some are reserved for Miralis, others are usable by the firmware). The hard part with multiplexing is taking into account all of the interactions that the multiplexed resources has with other resources/events. For instance there are counter inhibit registers, which would also need to be multiplexed to properly reproduce the semantic of the performance counters.

**Comment by francois141** [comment]
I didn't know we could reset the counter. In that case my implementation would not work. Let's see what we could do here. Maybe we can read from CLINT as alternative. What do you think about that? It seems CLINT has no reset
