### ISSUE TITLE
``just test`` don't work with multiple cores

### ISSUE THREAD

**Issue by francois141** [CharlyCst/miralis#252]

**Comment by CharlyCst** [comment]
As I motioned in https://github.com/CharlyCst/miralis/pull/254#issuecomment-2450322448 I think we should keep our firmware integration test on single core, they are designed to test specific aspects of Miralis and we should make them multi-core only if that is the part we want to exercise (e.g. the new IPI test is multi-core).

We could run Linux/OpenSBI on multi-core though.

**Comment by CharlyCst** [comment]
So I ran a few tests, it seems Linux doesn't boot all the cores on QEMU with 2 harts:

```
[    0.034383] smp: Bringing up secondary CPUs ...
[    1.405265] CPU1: failed to come online
[    1.406596] smp: Brought up 1 node, 1 CPU
```

Because Linux boots even if some cores are failing that doesn't cause the tests to fail.
