### ISSUE TITLE
Reduce the total number of test payloads

### ISSUE THREAD

**Issue by CharlyCst** [CharlyCst/miralis#35]
We started accumulating a lot of test payloads, and that's great!
However, there is a lot of redundancy in our tests as of now, with some payloads only checking a few CSR registers. It approach is not going to scale as we implement more and more features.

It is probably time for some refactoring to group tests into fewer payloads, maybe by testing multiple CSRs in a single payload.
Also, note that implementing #19 would provide the ability to print, and thus to use `assert!` with string comments to indicate which tests failed. Once implemented, that would make it easy to detect what went wrong in a payload in case of crash, despite testing a few functionalities at once.

**Comment by francois141** [comment]
@CharlyCst What do you mean exactly? I can take care of it
