### ISSUE TITLE
Try running Zephyr

### ISSUE THREAD

**Issue by CharlyCst** [CharlyCst/miralis#73]
Zephyr is a real time OS (RTOS), which happens to support our StarFive board ([doc](https://docs.zephyrproject.org/latest/boards/starfive/visionfive2/doc/index.html)).
Can we get Zphyr to run on top of Mirage?

- [x] Investigate Zephyr (does it use S-mode? U-mode?)
- [x] Try running Zephyr on Mirage
- [x] Create Zephyr binaries and add them to the CI?

**Comment by CharlyCst** [comment]
So far we created a Zephyr binary, but we do not run it in the CI because it loops indefinitely between the two thread. To run in in the CI we would need to build a modified version of de demo Zephyr application that exists after 1 or 2 timer interrupts.

**Comment by NoeTerrier** [comment]
This issue was closed by #123
