### ISSUE TITLE
Detect Physical Memory Protection (PMP) registers

### ISSUE THREAD

**Issue by francois141** [CharlyCst/miralis#86]
Physical Memory Protection (PMP) registers are not guaranteed to be available in all RISC-V hardware implementations. The presence of these registers depends on the specific design and configuration of the RISC-V processor, as they are an optional feature within the RISC-V specification. Therefore we need to detect the presence or absence of those registers.

Overall this should be part of a bigger effort to detect available hardware features and expose virtual registers accordingly, similar to e.g. https://github.com/CharlyCst/mirage/issues/62.

**Comment by CharlyCst** [comment]
Done with #119
